"""增加地区字段

Revision ID: b45c7b6f053d
Revises: 
Create Date: 2020-09-28 22:47:26.746001

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b45c7b6f053d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
                    sa.Column('place_id', sa.Integer(), nullable=False),
                    sa.Column('place_name', sa.String(length=50), nullable=True),
                    sa.Column('place_order', sa.Integer(), nullable=True),
                    sa.Column('parent_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['parent_id'], ['area.place_id'], ),
                    sa.PrimaryKeyConstraint('place_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('area')
    # ### end Alembic commands ###
