"""修改价格字段类型

Revision ID: ea2c7b5d9d5a
Revises: b45c7b6f053d
Create Date: 2020-09-29 17:35:33.363291

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ea2c7b5d9d5a'
down_revision = 'b45c7b6f053d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_goods',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('goods_id', sa.Integer(), nullable=True),
                    sa.Column('order_id', sa.Integer(), nullable=True),
                    sa.Column('price', sa.DECIMAL(), nullable=True),
                    sa.Column('order_price', sa.DECIMAL(), nullable=True),
                    sa.Column('order_active', sa.Integer(), nullable=True),
                    sa.Column('amount', sa.Integer(), nullable=True),
                    sa.Column('discount', sa.DECIMAL(), nullable=True),
                    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_goods')
    # ### end Alembic commands ###
